### ISSUE TITLE
Tutorial to Clipboard. Where is it?

### ISSUE THREAD

**Issue by cradino** [justinmchase/Clipboard#6]
I have been using Thornsoft Clipmate for more than a decade, which is a paid and effective application.
But as I am passionate about free software whenever I see something versing the windows clips in open source experiment.
So I tried and use the application [1clipboard](http://1clipboard.io/#section_feature) What I like but I think it is very limited ..
 Recently I found the Clipboard application in the Microsoft store and I say, feeling ashamed that I can not even see how it works.
Someone can help me?

**Comment by justinmchase** [comment]
Because this is a windows store app this is simply meant to be a bridge between the new "share" system and the old "clipboard" system in windows. Older desktop applications do not have the ability to share content or act as a share target. This clipboard app can do that for you, acting as a way to share whatever is in your clipboard or receive share data and put it into your clipboard for you.

# Sharing from the app
If you run the app, there is a Share button. When pressed it shares whatever is currently in your clipboard to another app. You'll notice the sidebar open on the right side, you pick an app and the contents of your clipboard will be shared into that app.

# Sharing to the clipboard
Other windows apps can share content between each other. Older windows desktop apps do not have the ability to be shared to/from. From a windows store app use its share function, on the right side of the screen will pop up a list of apps to pick as a share target. Select clipboard, when it pops up there is a Copy button. Press the copy button and the contents that were shared will be copied into your clipboard.

You can then go into your windows desktop app and Paste that content.

**Comment by justinmchase** [comment]
Specific scenarios:

# Email a photo

- Open windows explorer
- Navigate to your Photos directory
- Select an image file
- Press Ctrl+C (Copy)
- Open the Clipboard application
- Press the Share Button
- In the list of share app, pick an Email application

## Expected Results
In the share panel the email application will allow you to send an email with the photo you copied embedded.

# Share an image to your desktop

- Open windows explorer
- Navigate to your photos directory
- Open an image with Windows Preview application
- Press the Share button
- In the list of share applications, pick the Clipboard application
- Press the Copy button
- Put focus on your desktop
- Press Ctrl+V (Paste)

## Expected results
The image file is copied to your desktop.

**Comment by justinmchase** [comment]
Here is a little more on sharing in case you're not sure what I'm talking about:

http://www.groovypost.com/howto/share-files-windows-10-sans-charms-bar/
